spring.application.name=ZuperTV
# El puerto de tu servidor web
server.port=8080

# Conexión a PostgreSQL (Creá una base de datos llamada 'streaming_db' en tu pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/streaming_db
spring.datasource.username=postgres
spring.datasource.password=2079562
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Crea o actualiza las tablas automáticamente basándose en tus @Entity
spring.jpa.hibernate.ddl-auto=create
# Dialecto específico para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Le dice a Spring que ejecute el data.sql DESPUÉS de crear las tablas
spring.jpa.defer-datasource-initialization=true

# 1. Le dice a Spring: "Sí, quiero que inicialices la BD con mi archivo data.sql aunque sea PostgreSQL"
spring.sql.init.mode=always

# 2. Le dice a Spring: "Pero por favor, esperá a que Hibernate termine de crear las tablas primero"
spring.jpa.defer-datasource-initialization=true
